version: '3'
services:
  metube:
    build: .
    container_name: metube
    restart: unless-stopped
    ports:
      - '8081:8081'
    volumes:
      - /media/youtube:/downloads
    environment:
      - 'YTDL_OPTIONS={"writeinfojson": true, "writethumbnail": true, "postprocessors": [{"key": "FFmpegMetadata"}, {"key": "EmbedThumbnail", "already_have_thumbnail": true}]}'
