version: '3'
services:
  metube:
    build: .
    container_name: metube
    ports:
      - '8081:8081'
    volumes:
      - ./downloads:/downloads
    environment:
      - 'YTDL_OPTIONS={"writeinfojson": true, "writethumbnail": true, "postprocessors": [{"key": "FFmpegMetadata"}, {"key": "EmbedThumbnail", "already_have_thumbnail": true}]}'
      - 'DELETE_FILE_ON_TRASHCAN=true'
